### ISSUE TITLE
Doesn't work with silencer 1.1.0

### ISSUE THREAD

**Issue by mhenrixon** [emartech/ezlog#6]
Seems like something changed in how the silencer gem is initialised.

```ruby
2) Sessions POST /sessions when remember_me is checked writes an encrypted auth_token cookie
     Failure/Error: post sessions_path, params: params

     ArgumentError:
       invalid log level:
     # /Users/mhenrixon/.rubies/ruby-3.1.1/lib/ruby/3.1.0/logger.rb:268:in `level='
     # ./vendor/ruby/3.1.0/gems/rack-2.2.3/lib/rack/logger.rb:14:in `call'
     # ./vendor/ruby/3.1.0/gems/silencer-1.1.0/lib/silencer/rack/logger.rb:31:in `call'
     # ./vendor/ruby/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
     # ./vendor/ruby/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/request_id.rb:26:in `call'
     # ./vendor/ruby/3.1.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
     # ./vendor/ruby/3.1.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
     # ./vendor/ruby/3.1.0/gems/activesupport-7.0.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
     # ./vendor/ruby/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
     # ./vendor/ruby/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/static.rb:23:in `call'
     # ./vendor/ruby/3.1.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
     # ./vendor/ruby/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
     # ./vendor/ruby/3.1.0/gems/railties-7.0.2.3/lib/rails/engine.rb:530:in `call'
     # ./vendor/ruby/3.1.0/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # ./vendor/ruby/3.1.0/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # ./vendor/ruby/3.1.0/gems/rack-test-1.1.0/lib/rack/test.rb:119:in `request'
     # ./vendor/ruby/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/testing/integration.rb:279:in `process'
     # ./vendor/ruby/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/testing/integration.rb:22:in `post'
     # ./vendor/ruby/3.1.0/gems/actionpack-7.0.2.3/lib/action_dispatch/testing/integration.rb:370:in `post'
     # ./spec/requests/sessions_spec.rb:43:in `block (4 levels) in <main>'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:263:in `instance_exec'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:263:in `block in run'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:486:in `block in run'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:352:in `call'
     # ./vendor/ruby/3.1.0/gems/rspec-rails-5.1.1/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:390:in `execute_with'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:352:in `call'
     # ./vendor/ruby/3.1.0/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <main>'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:390:in `execute_with'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:352:in `call'
     # ./vendor/ruby/3.1.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/failure_aggregator.rb:10:in `block in aggregate'
     # ./vendor/ruby/3.1.0/gems/rspec-support-3.11.0/lib/rspec/support.rb:118:in `with_failure_notifier'
     # ./vendor/ruby/3.1.0/gems/rspec-expectations-3.11.0/lib/rspec/expectations/failure_aggregator.rb:8:in `aggregate'
     # ./vendor/ruby/3.1.0/gems/rspec-expectations-3.11.0/lib/rspec/matchers.rb:306:in `aggregate_failures'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:2251:in `block in define_built_in_hooks'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:390:in `execute_with'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:352:in `call'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:486:in `run'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:259:in `run'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:642:in `map'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:642:in `run_examples'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:607:in `run'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `block in run'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `map'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `run'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `block in run'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `map'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `run'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `map'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:2068:in `with_suite_hooks'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/reporter.rb:74:in `report'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:115:in `run_specs'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:89:in `run'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:71:in `run'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:45:in `invoke'
     # ./vendor/ruby/3.1.0/gems/rspec-core-3.11.0/exe/rspec:4:in `<main>'
     # ./vendor/ruby/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
     # ./vendor/ruby/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
     # ./vendor/ruby/3.1.0/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
     # <internal:/Users/mhenrixon/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
     # <internal:/Users/mhenrixon/.rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
     # -e:1:in `<main>'
```

**Comment by mhenrixon** [comment]
Never mind, gem isn't even loaded in the test environment. Forgot I changed that....
